server:
  port: ${PORT:8083}

---

spring:
  data:
    rest:
      base-path: /api
  application:
    name: livro-service
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static
---